src/cruise_literature/cruise_literature/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from cruise_literature import settings

urlpatterns = [
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("", include("document_search.urls")),
    path("", include("users.urls")),
    path("", include("literature_review.urls")),
    path("", include("citation_screening.urls")),
    path("", include("document_classification.urls")),
    path("", include("organisations.urls")),
]

src/cruise_literature/home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("index", views.home, name="index"),
    path("about/", views.about, name="about"),
    path("faq/", views.faq, name="faq"),
]

src/cruise_literature/literature_review/urls.py
from django.urls import path


from . import views

app_name = "literature_review"
urlpatterns = [
    path(
        "literature_review/",
        views.literature_review_home,
        name="literature_review_home",
    ),
    path(
        "literature_review/<int:review_id>/",
        views.review_details,
        name="review_details",
    ),
    path(
        "literature_review/<int:review_id>/add_seed_studies",
        views.add_seed_studies,
        name="add_seed_studies",
    ),
    path(
        "literature_review/<int:review_id>/edit",
        views.edit_review,
        name="edit_review",
    ),
    path(
        "literature_review/<int:review_id>/import_papers",
        views.import_papers,
        name="import_papers",
    ),
    path("export_review/<int:review_id>/", views.export_review, name="export_review"),
    path("delete_review/<int:review_id>/", views.delete_review, name="delete_review"),
    path("manage_review/<int:review_id>/", views.manage_review, name="manage_review"),
    path("add_review_member/<int:review_id>", views.add_review_member, name="add_review_member"),
    path("remove_review_member/<int:review_id>", views.remove_review_member, name="remove_review_member"),
    path("create_review/", views.create_new_review, name="create_new_review"),
    path("update_search/<int:review_id>", views.update_search, name="update_search"),
]

src/cruise_literature/organisations/urls.py
from django.urls import path

from . import views

app_name = "organisations"
urlpatterns = [
    path(
        "view_all_organisations/",
        views.view_all_organisations,
        name="view_all_organisations",
    ),
    path(
        "view_organisation/<int:organisation_id>/",
        views.view_organisation,
        name="view_organisation",
    ),
    path(
        "edit_organisation/<int:organisation_id>/",
        views.view_organisation,
        name="edit_organisation",
    ),  # TODO: Implement edit_organisation
    path(
        "delete_organisation/<int:organisation_id>/",
        views.delete_organisation,
        name="delete_organisation",
    ),
    path(
        "view_organisation/<int:organisation_id>/add_member/",
        views.add_member,
        name="add_member",
    ),
    path(
        "remove_member/<int:organisation_id>/<int:user_id>",
        views.remove_member,
        name="remove_member",
    ),
    path("create_organisation/", views.create_organisation, name="create_organisation"),
    path(
        "find_organisations/<int:user_id>",
        views.find_organisations,
        name="find_organisation",
    ),
]

src/cruise_literature/organisations/models.py
import logging

from django.conf import settings
from django.db import models, transaction
from django.utils.translation import gettext_lazy as _

logger = logging.getLogger(__name__)


class Organisation(models.Model):
    """Model class representing an organisation."""

    title = models.CharField(_("organisation title"), max_length=1000, null=False)
    description = models.TextField(_("organisation description"), null=True, blank=True)

    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="organisations",
        through="OrganisationMember",
    )

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="organisation",
        verbose_name=_("created_by"),
    )

    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated at"), auto_now=True)

    def remove_user(self, user):
        if not self.members.filter(pk=user.pk).exists():
            logger.debug("User does not exist in organisation.")
            return

        with transaction.atomic():
            om = OrganisationMember.objects.get(member=user, organisation=self)
            om.delete()

            return om

    @property
    def number_of_members(self):
        """Return the number of members in the organisation."""
        return self.members.count()

    def __str__(self):
        return self.title


class OrganisationMember(models.Model):
    """A member of an organisation."""

    member = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="om_through",
        help_text="User ID",
    )
    organisation = models.ForeignKey(
        Organisation,
        on_delete=models.CASCADE,
        help_text="Organisation ID",
    )

    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated at"), auto_now=True)

    roles_choices = [
        ("AD", "Admin"),
        ("ME", "Member"),
        ("GU", "Guest"),
    ]
    role = models.CharField(
        max_length=2,
        choices=roles_choices,
        default="ME",
    )

    @classmethod
    def find_by_user(cls, user_or_user_pk, organisation_pk):
        from users.models import User

        user_pk = (
            user_or_user_pk.pk if isinstance(user_or_user_pk, User) else user_or_user_pk
        )
        return OrganisationMember.objects.get(
            user=user_pk, organisation=organisation_pk
        )

    class Meta:
        ordering = ["pk"]

src/cruise_literature/organisations/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.forms import (
    Textarea,
    ModelForm,
    TextInput,
    Select,
)

from .models import Organisation, OrganisationMember


class OrganisationForm(ModelForm):
    """Form for creating an organisation."""

    class Meta:
        model = Organisation
        fields = ["title", "description", "admins"]
        widgets = {
            "title": TextInput(attrs={"class": "form-control"}),
            "description": Textarea(attrs={"class": "form-control"}),
        }

    admins = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        help_text="Select the users who will be administrators of this organisation.",
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super(OrganisationForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        organisation = super(OrganisationForm, self).save(commit=False)
        organisation.created_by = self.user
        if commit:
            organisation.save()
            admins_list = list(self.cleaned_data["admins"])
            if self.user not in admins_list:
                admins_list.append(self.user)
            for _user in admins_list:
                member = OrganisationMember(
                    member=_user, organisation=organisation, role="AD"
                )
                member.save()

        return organisation


class OrganisationMemberForm(ModelForm):
    """Form for adding a member to an organisation."""

    class Meta:
        model = OrganisationMember
        fields = ["member", "role"]
        widgets = {
            "member": Select(attrs={"class": "form-control"}),
            "role": Select(attrs={"class": "form-control"}),
        }

    def __init__(self, *args, **kwargs):
        self.organisation = kwargs.pop("organisation", None)
        super(OrganisationMemberForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        org_member = super(OrganisationMemberForm, self).save(commit=False)
        org_member.organisation = self.organisation
        if commit:
            org_member.save()
        return org_member

src/cruise_literature/organisations/views.py
from django.contrib.admin.views.decorators import staff_member_required

# Create your views here.
from django.contrib.auth.decorators import user_passes_test, login_required
from django.http import JsonResponse
from django.shortcuts import redirect, render, get_object_or_404

from literature_review.models import LiteratureReview
from organisations.forms import OrganisationForm, OrganisationMemberForm
from organisations.models import Organisation, OrganisationMember
from users.models import User


@user_passes_test(lambda u: u.is_superuser)
@staff_member_required
def create_organisation(request):
    """View for creating an organisation."""
    if request.method == "POST":
        form = OrganisationForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect("organisations:view_organisations")
    else:
        form = OrganisationForm(user=request.user)
    return render(request, "organisations/create_organisation.html", {"form": form})


@user_passes_test(lambda u: u.is_superuser)
@staff_member_required
def view_all_organisations(request):
    """View all organisations."""
    organisations = Organisation.objects.all()
    for organisation in organisations:
        organisation.n_reviews = len(
            LiteratureReview.objects.filter(organisation=organisation)
        )

    return render(
        request,
        "organisations/view_all_organisations.html",
        {"organisations": organisations},
    )


@login_required
def view_organisation(request, organisation_id):
    """View all people in an organisation."""
    organisation = get_object_or_404(Organisation, pk=organisation_id)
    members = OrganisationMember.objects.filter(organisation=organisation)
    if not request.user.is_superuser and request.user not in organisation.members.all():
        return redirect("home")

    if request.user.is_superuser:
        current_user_role = "AD"
    else:
        current_user_role = OrganisationMember.objects.filter(
            member=request.user, organisation=organisation
        ).values_list("role", flat=True)[0]

    if current_user_role in ["AD", "ME"]:
        literature_reviews = LiteratureReview.objects.filter(organisation=organisation)
    else:
        literature_reviews = []

    return render(
        request,
        "organisations/view_organisation.html",
        {
            "organisation": organisation,
            "members": members,
            "current_user_role": current_user_role,
            "literature_reviews": literature_reviews,
        },
    )


@login_required
def add_member(request, organisation_id):
    """Add a member to an organisation."""
    organisation = get_object_or_404(Organisation, pk=organisation_id)
    if not request.user.is_superuser and "AD" not in OrganisationMember.objects.filter(
        member=request.user, organisation=organisation
    ).values_list("role", flat=True):
        return redirect("home")

    if request.method == "POST":
        form = OrganisationMemberForm(request.POST, organisation=organisation)
        if form.is_valid():
            form.save()
            return redirect(
                "organisations:view_organisation", organisation_id=organisation_id
            )
    else:
        form = OrganisationMemberForm(organisation=organisation)
        form.fields["member"].queryset = User.objects.exclude(
            om_through__organisation=organisation
        )
    return render(
        request,
        "organisations/add_member.html",
        {"form": form, "organisation": organisation},
    )


@login_required
def remove_member(request, organisation_id, user_id):
    """Remove a member from an organisation."""
    organisation = get_object_or_404(Organisation, pk=organisation_id)
    if not request.user.is_superuser and "AD" not in OrganisationMember.objects.filter(
        member=request.user, organisation=organisation
    ).values_list("role", flat=True):
        return redirect("home")

    if request.method == "GET":
        user = get_object_or_404(User, pk=user_id)
        organisation.remove_user(user=user)
        return redirect(
            "organisations:view_organisation", organisation_id=organisation_id
        )
    return redirect("organisations:view_organisation", organisation_id=organisation_id)


def delete_organisation(request, organisation_id):
    """Delete an organisation."""
    organisation = get_object_or_404(Organisation, pk=organisation_id)
    if not request.user.is_superuser and "AD" not in OrganisationMember.objects.filter(
        member=request.user, organisation=organisation
    ).values_list("role", flat=True):
        return redirect("home")

    if request.method == "GET":
        organisation.delete()
        return redirect("organisations:view_all_organisations")
    return redirect("organisations:view_all_organisations")


def find_organisations(request, user_id):
    """Find organisations for a user and returns json."""
    user = get_object_or_404(User, pk=user_id)
    organisations = Organisation.objects.filter(members=user)
    return JsonResponse(
        [
            {"id": organisation.id, "title": organisation.title}
            for organisation in organisations
        ],
        safe=False,
    )

src/cruise_literature/templates/organisations/add_member.html
{% extends '_base_templates/_base.html' %}

{% block content %}
    <div class="register">
        <h1 class="title is-1">Create new organisation</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}

            <div>
                <button type="submit" class="button is-link">Add member</button>
            </div>
        </form>

    </div>
    {% include "_base_templates/_footer.html" %}
{% endblock %}

src/cruise_literature/templates/organisations/create_organisation.html
{% extends '_base_templates/_base.html' %}

{% block content %}
    <div class="register">
        <h1 class="title is-1">Create new organisation</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}

            <div>
                <button type="submit" class="button is-link">Create organisation</button>
            </div>
        </form>

    </div>
    {% include "_base_templates/_footer.html" %}
{% endblock %}

src/cruise_literature/templates/organisations/view_all_organisations.html
{% extends '_base_templates/_base.html' %}

{% block content %}
    <div class="card">
        <div class="card-content">
            <h1 class="title is-1">
                Organisations
                <a href="{% url 'organisations:create_organisation' %}" class="button is-link ml-5 mt-3">
                    Create new organisation
                </a>
            </h1>
        </div>
    </div>

    <div class="card">
        <div class="card-content">
            <table class="table is-striped table is-fullwidth is-hoverable">
                <thead>
                <tr>
                    <th>Number</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Members</th>
                    <th>Reviews</th>
                </tr>
                </thead>
                <tbody>
                {% for organisation in organisations %}
                    <tr>
                        <th>{{ forloop.counter }}</th>
                        <td><a href="{% url 'organisations:view_organisation' organisation.id %}">{{ organisation.title }}</a></td>
                        <td>{{ organisation.description }}</td>
                        <td>{{ organisation.number_of_members }}</td>
                        <td>{{ organisation.n_reviews }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    {% include "_base_templates/_footer.html" %}
{% endblock %}

src/cruise_literature/templates/organisations/view_organisation.html
{% extends '_base_templates/_base.html' %}

{% block content %}
    <div class="card">
        <div class="card-content">
            <h1 class="title is-1">
                Organisation: {{ organisation.title }}
            </h1>
        </div>
    </div>
    <div class="card">
        <h2>Members</h2>
        <div class="card-content">
            <table class="table is-striped table is-fullwidth is-hoverable">
                <thead>
                <tr>
                    <th>Number</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>First name</th>
                    <th>Last name</th>
                    {% if current_user_role == 'AD' or current_user_role == 'ME' %}
                        <th>Role</th>
                    {% endif %}
                    {% if current_user_role == "AD" %}
                        <th></th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for member in members %}
                    <tr>
                        <th>{{ forloop.counter }}</th>
                        <td>{{ member.member.username }}</td>
                        <td>{{ member.member.email }}</td>
                        <td>{{ member.member.first_name }}</td>
                        <td>{{ member.member.last_name }}</td>
                        {% if current_user_role == 'AD' or current_user_role == 'ME' %}

                            <td>{{ member.role }}</td>
                        {% endif %}
                        {% if current_user_role == "AD" %}
                            <td>
                                <button class="js-modal-trigger button is-danger is-small"
                                        data-target="modal-remove-member-{{ member.member.id }}">
                                    Remove member
                                </button>
                            </td>
                        {% endif %}
                    </tr>
                    <div id="modal-remove-member-{{ member.member.id }}" class="modal">
                        <div class="modal-background"></div>
                        <div class="modal-content">
                            <div class="box">
                                <p>Are you sure that you want to remove the user {{ member.member.username }}?</p>
                                <a href="{% url 'organisations:remove_member' organisation.id member.member.id %}"
                                   class="button is-danger is-small">Yes</a>
                            </div>
                        </div>
                        <button class="modal-close is-large" aria-label="close"></button>
                    </div>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card">
            <h2>Reviews</h2>
            <div class="card-content">
                <table class="table is-striped table is-fullwidth is-hoverable">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Discipline</th>
                        <th>#PDFs / #papers</th>
                        <th>#Screened (%)</th>
                        <th>Decisions (I / ? / E)</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for review in literature_reviews %}
                        <tr>
                            <th>{{ forloop.counter }}</th>
                            <td><a href="{% url 'literature_review:review_details' review.id %}">{{ review.title }}</a>
                            </td>
                            <td>{{ review.description }}</td>
                            <td>{{ review.discipline }}</td>
                            <td>{{ review.number_of_pdfs }} / {{ review.number_of_papers }}</td>
                            <td>{{ review.number_of_screened }} ({{ review.percentage_screened }}%)</td>
                            <td>{{ review.decisions_count.0 }} / {{ review.decisions_count.1 }}
                                / {{ review.decisions_count.2 }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card-content">
            {% if current_user_role == "AD" %}
                <a href="{% url 'organisations:add_member' organisation.id %}" class="button is-primary">Add member</a>
                <a class="button" disabled>Edit</a>
                <button class="js-modal-trigger button is-danger" data-target="modal-delete-organisation">
                    Delete organisation
                </button>
                <a href="{% url 'organisations:view_all_organisations' %}" class="button is-link">Back</a>
            {% endif %}

            <div id="modal-delete-organisation" class="modal">
                <div class="modal-background"></div>
                <div class="modal-content">
                    <div class="box">
                        <p>Are you sure that you want to remove the organisation {{ organisation.title }}?</p>
                        <a href="{% url 'organisations:delete_organisation' organisation.id %}"
                           class="button is-danger is-small">Yes</a>
                    </div>
                </div>
                <button class="modal-close is-large" aria-label="close"></button>
            </div>

        </div>
    </div>
    {% include "_base_templates/_footer.html" %}
{% endblock %}