src/cruise_literature/cruise_literature/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from cruise_literature import settings

urlpatterns = [
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("", include("document_search.urls")),
    path("", include("users.urls")),
    path("", include("literature_review.urls")),
    path("", include("citation_screening.urls")),
    path("", include("document_classification.urls")),
    path("", include("organisations.urls")),
]

src/cruise_literature/home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("index", views.home, name="index"),
    path("about/", views.about, name="about"),
    path("faq/", views.faq, name="faq"),
]

src/cruise_literature/literature_review/urls.py
from django.urls import path


from . import views

app_name = "literature_review"
urlpatterns = [
    path(
        "literature_review/",
        views.literature_review_home,
        name="literature_review_home",
    ),
    path(
        "literature_review/<int:review_id>/",
        views.review_details,
        name="review_details",
    ),
    path(
        "literature_review/<int:review_id>/add_seed_studies",
        views.add_seed_studies,
        name="add_seed_studies",
    ),
    path(
        "literature_review/<int:review_id>/edit",
        views.edit_review,
        name="edit_review",
    ),
    path(
        "literature_review/<int:review_id>/import_papers",
        views.import_papers,
        name="import_papers",
    ),
    path("export_review/<int:review_id>/", views.export_review, name="export_review"),
    path("delete_review/<int:review_id>/", views.delete_review, name="delete_review"),
    path("manage_review/<int:review_id>/", views.manage_review, name="manage_review"),
    path("add_review_member/<int:review_id>", views.add_review_member, name="add_review_member"),
    path("remove_review_member/<int:review_id>", views.remove_review_member, name="remove_review_member"),
    path("create_review/", views.create_new_review, name="create_new_review"),
    path("update_search/<int:review_id>", views.update_search, name="update_search"),
]

src/cruise_literature/organisations/urls.py
from django.urls import path

from . import views

app_name = "organisations"
urlpatterns = [
    path(
        "view_all_organisations/",
        views.view_all_organisations,
        name="view_all_organisations",
    ),
    path(
        "view_organisation/<int:organisation_id>/",
        views.view_organisation,
        name="view_organisation",
    ),
    path(
        "edit_organisation/<int:organisation_id>/",
        views.view_organisation,
        name="edit_organisation",
    ),  # TODO: Implement edit_organisation
    path(
        "delete_organisation/<int:organisation_id>/",
        views.delete_organisation,
        name="delete_organisation",
    ),
    path(
        "view_organisation/<int:organisation_id>/add_member/",
        views.add_member,
        name="add_member",
    ),
    path(
        "remove_member/<int:organisation_id>/<int:user_id>",
        views.remove_member,
        name="remove_member",
    ),
    path("create_organisation/", views.create_organisation, name="create_organisation"),
    path(
        "find_organisations/<int:user_id>",
        views.find_organisations,
        name="find_organisation",
    ),
]

src/cruise_literature/templates/_base_templates/_base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Cruise-literature{% endblock %}</title>
    <meta name="description" content="">
    <link rel="shortcut icon" type="image/x-icon" href={% static 'favicon/favicon.ico' %}/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <script src="{% static 'js/concept-map.js' %}"></script>
    {# TODO move these scripts somewhere else #}
    <script src="{% static 'js/sort-paginate-table.js' %}"></script>
    <script src="{% static 'js/modal.js' %}"></script>
    {%block head%}
    {%endblock%}
</head>

<body>
    {% include "_base_templates/_header.html" %}
    {%block content%}
    {%endblock%}
</body>
</html>

src/cruise_literature/templates/_base_templates/_footer.html
<footer class="footer">
    <p>
        © 2023 DoSSIER Project | <a href="{% url 'about' %}">About</a>
    </p>
</footer>

src/cruise_literature/templates/_base_templates/_header.html
{% load static %}
<script>
    document.addEventListener('DOMContentLoaded', () => {

        // Get all "navbar-burger" elements
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

        // Check if there are any navbar burgers
        if ($navbarBurgers.length > 0) {

            // Add a click event on each of them
            $navbarBurgers.forEach(el => {
                el.addEventListener('click', () => {

                    // Get the target from the "data-target" attribute
                    const target = el.dataset.target;
                    const $target = document.getElementById(target);

                    // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                    el.classList.toggle('is-active');
                    $target.classList.toggle('is-active');

                });
            });
        }

    });
</script>

<nav class="navbar is-light navbar-height" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar__logo" href="{% url 'home' %}">
            <img src="{% static 'img/cruise-logo.png' %}" width="60" height="60">
        </a>
        <a role="button" data-target="userMenu" class="navbar-burger" aria-label="menu"
           aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
        {% if user.is_authenticated %}
            <a href="{% url 'literature_review:literature_review_home' %}" class="navbar-item">
                My reviews
            </a>
        {% endif %}
        {% if user.is_superuser %}
            <a href="{% url 'organisations:view_all_organisations' %}" class="navbar-item">
                Organisations
            </a>
        {% endif %}
    </div>
    {% if request.resolver_match.view_name == 'search_results' %}
        <div class="navbar-menu is-active">
            <div class="navbar-start">
                <form id="search_box" class="search-small" method="GET" action="/search">
                    <div class="search-small__input">
                        <input type="search" class="input mr-2" name="search_query" value="{{ search_query }}"
                               placeholder="Search" aria-label="Search"/>
                        <input type='hidden' name='source' value="reformulate_search">
                        <button class="button is-primary">Search</button>
                    </div>
                </form>
            </div>
        </div>
    {% endif %}
    <div class="navbar-menu" id="userMenu">
        <div class="navbar-end">
            <a href="{% url 'faq' %}" class="navbar-item">
                FAQ
            </a>
            {% if user.is_authenticated %}
                <div class="navbar-item has-dropdown is-hoverable">
                    <a href="{% url 'user_profile' %}" class="navbar-link">
                        {{ user.username|title }}
                    </a>
                    <div class="navbar-dropdown">
                        <a href="{% url 'user_profile' %}" class="navbar-item">
                            My profile
                        </a>
                        <a href="{% url 'literature_review:literature_review_home' %}" class="navbar-item">
                            My reviews
                        </a>
                        <hr class="navbar-divider">
                        <a href="{% url 'logout' %}" class="navbar-item">
                            Logout
                        </a>
                    </div>
                </div>
            {% else %}
                <a class="js-modal-trigger navbar-item" data-target="modal-sign-up">
                    <strong>Sign up</strong>
                </a>
                <a href="{% url 'login' %}" class="navbar-item">
                    Log in
                </a>
            {% endif %}
        </div>
    </div>
</nav>
<div class="messages message">
    {% if messages %}
        <ul class="messages__list ">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }} message-body"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

<div id="modal-sign-up" class="modal">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">You are about to create an account in CRUISE</p>
            <button class="delete" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
            <div class="block">
                CRUISE is a research project developed in the context of the <a href="https://dossier-project.eu/"
                                                                               target="_blank">DoSSIER</a> project.
                This project aims to develop a tool that will help researchers find and use the most relevant evidence in their work.
                We want to understand why specific papers are included and excluded from a literature review.
                To do this, we need to collect information about the literature review process by analysing how other researchers conduct their literature reviews.
            </div>
            <div class="block">
                We will aggregate your data with all the other participants and use it to write papers for conferences and journals.
                This data will also be published in a research data repository under a creative commons license.
                This will also allow prospective researchers to utilise it and drive insights for the future of reviewing literature.
            </div>
            <div class="block">
                There will be no data collected that allows for the revelation of your identity in any way.
                As a result, all information you provide will remain anonymous without leading to your identity in reporting the study results.
            </div>
            <div class="block">
                By creating an account, you acknowledge that you have read and understood the purpose of the project and
                have had all of your questions and concerns addressed
            </div>
            <div class="block">
                Do you have any further questions or concerns? If so please <a href="mailto:Wojciech.Kusa@tuwien.ac.at">contact us</a>.
                If not, please review the following and formally indicate your willingness to proceed.
            </div>
            <div class="block">
                Do you agree to the terms and conditions, and would you like to create an account?
            </div>
        </section>
        <footer class="modal-card-foot">
                <a class="button is-info" href="{% url 'register' %}" >
                    Yes, I agree and I would like to create an account
                </a>
            <button class="button ml-4">No, cancel</button>
        </footer>
    </div>
</div>