src/cruise_literature/citation_screening/urls.py
from django.urls import path

from . import views

app_name = "citation_screening"
urlpatterns = [
    path(
        "literature_review/<int:review_id>/automatic_screening",
        views.automatic_screening,
        name="automatic_screening",
    ),
    path(
        "literature_review/<int:review_id>/prompt_based_screening",
        views.prompt_based_screening,
        name="prompt_based_screening",
    ),
    path("screening_home/<int:review_id>/", views.screening_home, name="screening_home"),
    path("screen_papers/<int:review_id>/", views.screen_papers, name="screen_papers"),
    path(
        "screen_paper/<int:review_id>/<str:paper_id>/",
        views.screen_paper,
        name="screen_paper",
    ),
    path("literature_review/<int:review_id>/ditribute_papers", views.distribute_papers, name="distribute_papers"),
]

src/cruise_literature/cruise_literature/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from cruise_literature import settings

urlpatterns = [
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("", include("document_search.urls")),
    path("", include("users.urls")),
    path("", include("literature_review.urls")),
    path("", include("citation_screening.urls")),
    path("", include("document_classification.urls")),
    path("", include("organisations.urls")),
]

src/cruise_literature/home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("index", views.home, name="index"),
    path("about/", views.about, name="about"),
    path("faq/", views.faq, name="faq"),
]

src/cruise_literature/literature_review/urls.py
from django.urls import path


from . import views

app_name = "literature_review"
urlpatterns = [
    path(
        "literature_review/",
        views.literature_review_home,
        name="literature_review_home",
    ),
    path(
        "literature_review/<int:review_id>/",
        views.review_details,
        name="review_details",
    ),
    path(
        "literature_review/<int:review_id>/add_seed_studies",
        views.add_seed_studies,
        name="add_seed_studies",
    ),
    path(
        "literature_review/<int:review_id>/edit",
        views.edit_review,
        name="edit_review",
    ),
    path(
        "literature_review/<int:review_id>/import_papers",
        views.import_papers,
        name="import_papers",
    ),
    path("export_review/<int:review_id>/", views.export_review, name="export_review"),
    path("delete_review/<int:review_id>/", views.delete_review, name="delete_review"),
    path("manage_review/<int:review_id>/", views.manage_review, name="manage_review"),
    path("add_review_member/<int:review_id>", views.add_review_member, name="add_review_member"),
    path("remove_review_member/<int:review_id>", views.remove_review_member, name="remove_review_member"),
    path("create_review/", views.create_new_review, name="create_new_review"),
    path("update_search/<int:review_id>", views.update_search, name="update_search"),
]

src/cruise_literature/home/views.py
from django.shortcuts import render
import random


def home(request):
    """
    Home page
    """
    if request.method == "GET":
        default_search_queries = [
            "Natural Language Processing",
            "Machine Learning",
            "Computational Biology",
            "Comparative Genomics",
            "High Energy Physics",
            "Cancer Research",
            "How to build a search engine?",
        ]
        return render(
            request,
            "home/home.html",
            {"default_query": random.choice(default_search_queries)},
        )


def about(request):
    """
    About page
    """
    if request.method == "GET":
        return render(
            request,
            "home/about.html",
        )


def faq(request):
    """
    FAQ page
    """
    if request.method == "GET":
        return render(
            request,
            "home/faq.html",
        )

src/cruise_literature/literature_review/views.py
import datetime
import hashlib
import json
from typing import Dict, List

import bibtexparser
import rispy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from requests import HTTPError

from users.models import User
from .forms import NewLiteratureReviewForm, EditLiteratureReviewForm
from .models import LiteratureReview
from utils.process_pdf import parse_doc_grobid


@login_required
def create_new_review(request):
    initial = {
        "exclusion_criteria": [
            "Paper written in language other than English",
            "Only title is available",
        ]
    }
    if request.method == "POST":
        form = NewLiteratureReviewForm(request.POST, user=request.user, initial=initial)
        if form.is_valid():
            form.save()
            title = form.cleaned_data.get("title")
            messages.success(request, f"New review created: {title}")
            return redirect(
                "literature_review:manage_review", review_id=form.instance.id
            )
        else:
            if "error_messages" in form:
                for msg in form.error_messages:
                    messages.error(request, f"{msg}: {form.error_messages[msg]}")
            elif "errors" in form:
                for msg in form.errors:
                    messages.error(request, f"{msg}: {form.errors[msg]}")

            return render(
                request=request,
                template_name="literature_review/create_literature_review.html",
                context={"form": form},
            )

    form = NewLiteratureReviewForm(user=request.user, initial=initial)
    form.fields["organisation"].queryset = form.fields["organisation"].queryset.filter(
        members=request.user
    )
    return render(
        request=request,
        template_name="literature_review/create_literature_review.html",
        context={"form": form},
    )


def update_criteria(
    current_criteria: Dict[str, List[Dict]],
    inclusion: List[str],
    exclusion: List[str],
    user_id: int,
) -> Dict[str, List[Dict]]:
    """
    Updates the criteria for a literature review. If a criterion is not in the
    current criteria, it is added. If it is in the current criteria but not in the new
    criteria, it is marked as inactive.

    :param current_criteria:
    :param inclusion:
    :param exclusion:
    :param user_id:
    :return:
    """
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    old_inclusion_text = [x["text"] for x in current_criteria["inclusion"]]
    old_exclusion_text = [x["text"] for x in current_criteria["exclusion"]]

    # add new inclusion criteria
    for inc in inclusion:
        if inc in old_inclusion_text:
            continue
        else:
            current_criteria["inclusion"].append(
                {
                    "id": f"in_{len(current_criteria['inclusion'])}",
                    "is_active": True,
                    "text": inc,
                    "comment": "",
                    "added_at": timestamp,
                    "added_by": user_id,
                    "updated_at": timestamp,
                    "updated_by": user_id,
                }
            )

    for exc in exclusion:
        if exc in old_exclusion_text:
            continue
        else:
            current_criteria["exclusion"].append(
                {
                    "id": f"ex_{len(current_criteria['exclusion'])}",
                    "is_active": True,
                    "text": exc,
                    "comment": "",
                    "added_at": timestamp,
                    "added_by": user_id,
                    "updated_at": timestamp,
                    "updated_by": user_id,
                }
            )

    # make is_active False for all criteria that are not in the new list
    for old_inc in old_inclusion_text:
        if old_inc not in inclusion:
            for inc in current_criteria["inclusion"]:
                if inc["text"] == old_inc:
                    inc["is_active"] = False
                    inc["updated_at"] = timestamp
                    inc["updated_by"] = user_id
                    break

    for old_exc in old_exclusion_text:
        if old_exc not in exclusion:
            for exc in current_criteria["exclusion"]:
                if exc["text"] == old_exc:
                    exc["is_active"] = False
                    exc["updated_at"] = timestamp
                    exc["updated_by"] = user_id
                    break

    return current_criteria


@login_required
def edit_review(request, review_id):
    review = get_object_or_404(LiteratureReview, pk=review_id)
    if request.user not in review.members.all():
        raise Http404("Review not found")

    if request.method == "POST":
        form = EditLiteratureReviewForm(request.POST, user=request.user)
        if form.is_valid():
            title = form.cleaned_data.get("title")
            review.title = title
            review.description = form.cleaned_data.get("description")
            new_criteria = update_criteria(
                current_criteria=review.criteria,
                inclusion=form.cleaned_data.get("inclusion_criteria"),
                exclusion=form.cleaned_data.get("exclusion_criteria"),
                user_id=request.user.id,
            )
            review.criteria = new_criteria
            review.tags = form.cleaned_data.get("tags")
            review.organisation = form.cleaned_data.get("organisation")
            review.save()
            messages.success(request, f"Review successfully edited: {title}")
            return render(
                request=request,
                template_name="literature_review/view_review.html",
                context={"review": review},
            )
        else:
            if "error_messages" in form:
                for msg in form.error_messages:
                    messages.error(request, f"{msg}: {form.error_messages[msg]}")
            return redirect("home")

    elif request.method == "GET":
        form = EditLiteratureReviewForm(
            user=request.user,
            initial={
                "title": review.title,
                "description": review.description,
                "inclusion_criteria": [
                    x["text"] for x in review.criteria["inclusion"] if x["is_active"]
                ],
                "exclusion_criteria": [
                    x["text"] for x in review.criteria["exclusion"] if x["is_active"]
                ],
                "tags": review.tags,
                "organisation": review.organisation,
            },
        )
        form.fields["organisation"].queryset = form.fields[
            "organisation"
        ].queryset.filter(members=request.user)
        return render(
            request=request,
            template_name="literature_review/edit_literature_review.html",
            context={"form": form, "review": review},
        )


@login_required
def literature_review_home(request):
    context = {
        "literature_reviews": LiteratureReview.objects.filter(members=request.user)
    }

    return render(
        request=request, template_name="literature_review/home.html", context=context
    )


@login_required
def review_details(request, review_id):
    review = get_object_or_404(LiteratureReview, pk=review_id)
    if request.user in review.members.all():
        return render(request, "literature_review/view_review.html", {"review": review})
    else:
        raise Http404("Review not found")


@login_required
def export_review(request, review_id):
    review = get_object_or_404(LiteratureReview, pk=review_id)
    if request.user not in review.members.all():
        raise Http404("Review not found")
    data = {
        "review_id": review.id,
        "title": review.title,
        "description": review.description,
        "search_queries": review.search_queries,
        "criteria": review.criteria,
        "papers": review.papers,
    }
    return HttpResponse(json.dumps(data, indent=2), content_type="application/json")


@login_required
def delete_review(request, review_id):
    review = get_object_or_404(LiteratureReview, pk=review_id)
    if request.user not in review.members.filter(
        om_through__member=request.user, om_through__role="AD"
    ):
        return redirect("literature_review:review_details", review_id=review_id)
    review.delete()
    return redirect("literature_review:literature_review_home")


def import_ris(file_data):
    """loads RIS file data into a list of papers"""
    file_data = "\n".join([line.strip() for line in file_data.splitlines()])
    entries = rispy.loads(file_data, skip_unknown_tags=True)
    papers = []
    for entry in entries:
        paper = {
            "title": entry.get("title"),
            "abstract": entry.get("abstract"),
            "authors": ", ".join(entry.get("authors")),
            "venue": entry.get("journal_name"),
            "publication_date": entry.get("year"),
            "doi": entry.get("doi"),
            "url": entry.get("url"),
            "n_references": None,
            "n_citations": None,
            "decisions": [],
            "decision": None,
            "screened": False,
            "included": False,
        }
        if paper["url"] is None:
            paper["url"] = f"https://www.doi.org/{paper['doi']}"
        paper["keywords"] = entry.get("keywords")
        paper["pdf"] = entry.get("pdf")
        paper["id"] = entry.get("id")

        if paper["id"] is None:
            paper["id"] = hashlib.md5(paper["title"].encode("utf-8")).hexdigest()
        papers.append(paper)

    return papers


def import_bib(file_data):
    bib_database = []
    for entry in bibtexparser.loads(file_data).entries:
        keywords = []
        if entry.get("keywords"):

src/cruise_literature/templates/literature_review/_review_header.html
{% if review.data_format_version > 2 %}
<a href="{% url 'literature_review:literature_review_home' %}" class="button is-info is-small">
    All reviews
</a>
<a href="{% url 'literature_review:review_details' review.id %}" class="button is-info is-small ml-4">
    Review home
</a>
<button class="js-modal-trigger ml-4 button is-info is-outlined is-small align-button-to-right"
    data-target="modal-screen-automatically-review-{{ review.id }}">
    Screen automatically
</button>
<a href="{% url 'literature_review:manage_review' review.id %}" class="ml-4 button is-info is-outlined is-small">
    Manage review
</a>
<a href="{% url 'literature_review:edit_review' review.id %}" class="ml-4 button is-info is-outlined is-small">
    Edit review
</a>
<a href="{% url 'literature_review:add_seed_studies' review.id %}" class="ml-4 button is-info is-outlined is-small">
    Add seed study
</a>
<a href="{% url 'literature_review:import_papers' review.id %}" class="ml-4 button is-info is-outlined is-small">
    Import papers
</a>
<a href="{% url 'literature_review:update_search' review.id %}" class="ml-4 button is-info is-outlined is-small">
    Update search
</a>
<a href="{% url 'literature_review:export_review' review.id %}" class="ml-4 button is-light is-small">
    Export results
</a>
{% if request.resolver_match.view_name == 'literature_review:review_details' %}
<button class="js-modal-trigger button is-danger disabled light is-small align-button-to-right"
        data-target="modal-delete-review-{{ review.id }}">
    Delete review
</button>
{% endif %}
{%  else %}
<a href="{% url 'literature_review:literature_review_home' %}" class="button is-info is-small">
    All reviews
</a>
<a href="{% url 'literature_review:review_details' review.id %}" class="button is-info is-small ml-4">
    Review home
</a>
<a class="ml-4 button is-info is-outlined is-small" disabled>
    Edit review
</a>
<a class="ml-4 button is-info is-outlined is-small" disabled>
    Add seed study
</a>
<a class="ml-4 button is-info is-outlined is-small" disabled>
    Update search
</a>
<a href="{% url 'literature_review:export_review' review.id %}" class="ml-4 button is-light is-small">
    Export results
</a>
<button class="js-modal-trigger button is-danger disabled light is-small align-button-to-right"
        data-target="modal-delete-review-{{ review.id }}">
    Delete review
</button>
{% endif %}

<div id="modal-screen-automatically-review-{{ review.id }}" class="modal">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Screen papers automatically</p>
            <button class="delete" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
            <div class="block">
                This will screen all the studies in the review using the screening criteria.
            </div>
            <div class="block">
                This may take a while. Approximately, to screen all documents it will take:
                <ul>
                    <li>For a binary classifier: around 30 seconds</li>
                    <li>For a prompt-based model: around {% widthratio review.number_of_papers 1 3 %} seconds</li>
            </div>
            <div class="block">
                As the process is based on the language model, you should check the results. You can access the original
                document by clicking on the title of the study or the 🌐 icon next to each study.
            </div>
            <div class="block">
                The results will be saved automatically. Sometimes the process will be interrupted. If this happens, you can
                resume the process by restarting the process. It will pick up where it left off.
            </div>
            <div class="block">
                Are you sure you want to continue?
            </div>
        </section>
        <footer class="modal-card-foot">
            {% if review.can_screen_automatically %}
                <a href="{% url 'citation_screening:automatic_screening' review.id %}" class="button is-info">
                    Use binary text classifier
                </a>
            {% else %}
                <a class="button is-info" disabled>
                    Use binary text classifier
                </a>
            {% endif %}
            <a href="{% url 'citation_screening:prompt_based_screening' review.id %}" class="ml-4 button is-info">
                Use prompt-based model
            </a>
            <button class="button ml-4">Cancel</button>
        </footer>
    </div>
</div>


<div id="modal-delete-review-{{ review.id }}" class="modal">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Are you sure that you want to delete this review?</p>
            <button class="delete" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
            <div class="block">
                Review title: <strong>'{{ review.title }}'</strong>
            </div>
            <div class="block">
                This will delete all papers, together with their eligibility decisions.
            </div>
        </section>
        <footer class="modal-card-foot">
            <a href="{% url 'literature_review:delete_review' review.id %}"
                   class="button is-danger">Yes, delete this review</a>
            <button class="button ml-4">Cancel</button>
        </footer>
    </div>
</div>

src/cruise_literature/templates/literature_review/add_review_member.html
{% extends '_base_templates/_base.html' %}
{% load static %}


{% block content %}
    <div class="card">
        <div class="card-header pl-4">
            {% include 'literature_review/_review_header.html' %}
        </div>
        <div class="card-content">
            <h1 class="title is-3">
                Review: {{ review.title }}
            </h1>
            <h5 class="is-5">Add new member to the review by username</h5>
            <hr/>
            <form method="POST" action="{% url 'literature_review:add_review_member' review.id %}">
                {% csrf_token %}
                <div class="field">
                    <label class="label">Username</label>
                    <div class="control">
                        <input class="input" type="text" name="username" placeholder="Username">
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <div class="select">
                            <select name="role">
                                <option value="ME">Member</option>
                                <option value="AD">Admin</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <button class="button is-link">Add</button>
                    </div>
                </div>
            </form>
            <hr/>
            <h5 class="is-5">Current members</h5>
            <p>
                {% for member in review.members.all %}
                    {{ member.username }}
                {% endfor %}
            </p>

        </div>

        <div class="card-footer pl-4">
            <a href="{% url 'literature_review:manage_review' review.id %}" class="button is-link is-small">
                Back
            </a>
        </div>
    </div>


    {% include "_base_templates/_footer.html" %}
{% endblock %}

src/cruise_literature/templates/literature_review/add_seed_studies.html
{% extends '_base_templates/_base.html' %}
{% block content %}
    <div class="card">
        <div class="card-header pl-4">
            {% include 'literature_review/_review_header.html' %}
        </div>
        <div class="card-content">
            <h1 class="title is-3">
                Review: {{ review.title }}
            </h1>
            <h5 class="is-5">Add new seed studies to your review</h5>
            <hr/>
            <form method="POST" action="{% url 'literature_review:add_seed_studies' review.id %}">
                {% csrf_token %}
                <textarea class="textarea is-small m-2" name="seed_studies_urls"
                          placeholder="Add URLs to your seed studies, one item per line..."></textarea>
                <hr/>
                <div id="file-js-example" class="file has-name m-2">
                    <label class="file-label">
                        <input class="file-input" type="file" name="seed_study_file" disabled>
                        <span class="file-cta">
                      <span class="file-icon">
                        <i class="fas fa-upload"></i>
                      </span>
                      <span class="file-label">
                        Choose additional PDF file (currently not supported)
                      </span>
                    </span>
                        <span class="file-name">
                      No file uploaded
                    </span>
                    </label>
                </div>
                <hr/>
                <div class="screen_paper_relevance control m-2 p-1 box">
                    <span class="is-size-6">Do you want to snowball references? (currently not supported)</span>
                    <label class="ml-4">
                        <input type="radio" name="domain_relevance" value="Yes" disabled>
                        <span class="button is-small">Yes</span>
                    </label>
                    <label class="ml-4">
                        <input type="radio" name="domain_relevance" value="No" disabled>
                        <span class="button is-small">No</span>
                    </label>
                </div>
                <button class="button is-info is-light is-fullwidth mt-5">Submit</button>
            </form>

            <script>
                const fileInput = document.querySelector('#file-js-example input[type=file]');
                fileInput.onchange = () => {
                    if (fileInput.files.length > 0) {
                        const fileName = document.querySelector('#file-js-example .file-name');
                        fileName.textContent = fileInput.files[0].name;
                    }
                }
            </script>

        </div>
    </div>


    {% include "_base_templates/_footer.html" %}
{% endblock %}

src/cruise_literature/templates/literature_review/home.html
{% extends '_base_templates/_base.html' %}

{% block content %}
    <div class="card">
        <div class="card-content">
            <h1 class="title is-1">
                My literature reviews
                <a href="{% url 'literature_review:create_new_review' %}" class="button is-link ml-5 mt-3">
                    Create new review
                </a>
            </h1>
        </div>
    </div>

    <div class="card">
        <div x-data="sortTable()" class="card-content">
            <table class="table is-striped table is-fullwidth is-hoverable">
                <thead>
                <tr>
                    <th @click="sortByColumn">Number</th>
                    <th @click="sortByColumn">Title</th>
                    <th @click="sortByColumn">Description</th>
                    <th @click="sortByColumn">Discipline</th>
                    <th @click="sortByColumn">Search queries</th>
                    <th @click="sortByColumn">#papers</th>
                    <th @click="sortByColumn">#PDFs</th>
                    <th @click="sortByColumn">#Screened</th>
                    <th @click="sortByColumn">% Screened</th>
                    <th @click="sortByColumn">Decisions (I / ? / E)</th>
                    <th>Manage Review</th>
                </tr>
                </thead>
                <tbody x-ref="tbody">
                {% for review in literature_reviews %}
                    <tr>
                        <th>{{ forloop.counter }}</th>
                        <td><a href="{% url 'literature_review:review_details' review.id %}">{{ review.title }}</a></td>
                        <td>{{ review.description }}</td>
                        <td>{{ review.discipline }}</td>
                        <td>
                            {% for query in review.search_queries %}
                                <span class="tag is-light">{{ query }}</span>
                            {% endfor %}
                        </td>
                        <td>{{ review.number_of_papers }}</td>
                        <td>{{ review.number_of_pdfs }}</td>
                        <td>{{ review.number_of_screened }}</td>
                        <td>{{ review.percentage_screened }}%</td>
                        <td>{{ review.decisions_count.0 }} / {{ review.decisions_count.1 }}
                            / {{ review.decisions_count.2 }}</td>
                        <td><a href="{% url 'literature_review:manage_review' review.id %}">Settings</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    {% include "_base_templates/_footer.html" %}
{% endblock %}

src/cruise_literature/templates/literature_review/manage_review.html
{% extends '_base_templates/_base.html' %}
{% load static %}


{% block content %}
    <div class="card">
        <div class="card-header pl-4">
            {% include 'literature_review/_review_header.html' %}
        </div>
        <div class="card-content">
            <div class="content">
                <div class="columns">
                    <div class="column is-8">
                        <h3 class="title is-3">{{ review.title }}</h3>
                    </div>
                    <div class="column is-4">
                        <div class="field is-grouped is-grouped-right">
                            <p class="control">
                                <a href="{% url 'literature_review:export_review' review.id %}" class="button is-link">
                                    Export
                                </a>
                            </p>
                            <p class="control">
                                <a href="{% url 'literature_review:delete_review' review.id %}"
                                   class="button is-danger">
                                    Delete
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="columns">
                    <div class="column is-8">
                        <div class="content">
                            <h4 class="title is-4">Description</h4>
                            <p>{{ review.description }}</p>
                            <h4 class="title is-4">Search queries</h4>
                            <p>{{ review.search_queries }}</p>
                            <h4 class="title is-4">Tags</h4>
                            <p>{{ review.tags }}</p>
                            <h4 class="title is-4">Members</h4>
                            <p>
                                {% for member in review.members.all %}
                                    {{ member.username }}
                                {% endfor %}
                            </p>
                            <p>
                                <a href="{% url 'literature_review:add_review_member' review.id %}">Add member</a>
                                |
                                <a href="{% url 'literature_review:remove_review_member' review.id %}">Remove member</a>
                            </p>
                        </div>
                    </div>
                    <div class="column is-4">
                        <div class="content">
                            <h4 class="title is-4">Organisation</h4>
                            <p>{{ review.organisation }}</p>
                            <h4 class="title is-4">Created</h4>
                            <p>{{ review.created_at }}</p>
                            <h4 class="title is-4">Updated</h4>
                            <p>{{ review.updated_at }}</p>
                            <h4 class="title is-4">Deadline</h4>
                            <p>{{ review.deadline }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box">
                <h4 class="title is-4">Prepare review for manual screening</h4>
                <p>
                    <a href="{% url 'citation_screening:distribute_papers' review.id %}" class="button is-link">
                        Distribute papers for manual screening
                    </a>
                </p>
            </div>

        </div>

        <div class="card-footer pl-4">
            <a href="{% url 'literature_review:literature_review_home' %}" class="button is-link is-small">
                Back
            </a>
        </div>
    </div>


    {% include "_base_templates/_footer.html" %}
{% endblock %}